### ISSUE TITLE
configure script insists libbinio is still broken even with latest libbinio code from git repo

### ISSUE THREAD

**Issue by sneakernets** [mywave82/opencubicplayer#36]
Referencing these links: https://github.com/adplug/libbinio/issues/2 https://github.com/adplug/libbinio/pull/8

Is this not the expected correct fix for this off-by-one issue? I compiled adplug and libbinio from scratch and seeing this check fail.

**Comment by mywave82** [comment]
I presume you are using a distro that provides libbinio (and libadplug) that is out-of-date and thereby trying to install the git master version.

The test that the configure script performs is a very simple one that actually exercises a very specific bug in the libbinio that prevents it from working with memory-mapped objects for most of the filetypes that adplug supports. The test-code that configure runs is this:
```
#include <binio.h>
#include <binstr.h>
#include <cstdlib>
#include <string.h>
#include <adplug/adplug.h>
#include <adplug/fprovide.h>
#include <string.h>
int
main ()
{
	binisstream *f = new binisstream((void *)"foobar", 6);
	long size;
	char test[6] = {1,2,3,4,5,6};
	f->seek(0, binio::End);
	size = f->pos();
	f->seek(0);
	if (f->readString(test, size) != 6) return -1;	
	/* test should contain "foobar" if all is correct */
	return memcmp(test, "foobar", 6);
}
```


Are you sure you have uninstalled the version of libbinio that the distro provides, else you are likely linking the test-binary that configure runs with that instead of the one you are installing from source.

**Comment by sneakernets** [comment]
> I presume you are using a distro that provides libbinio (and libadplug) that is out-of-date and thereby trying to install the git master version.

I'm compiling adplug and libbinio from source straight from the github repos. I uninstalled the distro versions and forced a recompile of everything. I am, however, running on an ARM CPU.

```
/usr/local/lib $ ls -l | grep libadplug
lrwxrwxrwx 1 root root       29 Sep  7 14:18 libadplug-2.3.4-beta.so.0 -> libadplug-2.3.4-beta.so.0.0.0
-rwxr-xr-x 1 root root   584736 Sep  7 14:18 libadplug-2.3.4-beta.so.0.0.0
-rw-r--r-- 1 root root  1215510 Sep  7 14:18 libadplug.a
-rwxr-xr-x 1 root root     1022 Sep  7 14:18 libadplug.la
lrwxrwxrwx 1 root root       29 Sep  7 14:18 libadplug.so -> libadplug-2.3.4-beta.so.0.0.0

/usr/local/lib $ whereis libadplug
libadplug: /usr/local/lib/libadplug.a /usr/local/lib/libadplug.so /usr/local/lib/libadplug.la

/usr/local/include/libbinio $ ls -l
-rw-r--r-- 1 root root 2821 Sep  7 12:02 binfile.h
-rw-r--r-- 1 root root 4584 Sep  7 12:02 binio.h
-rw-r--r-- 1 root root 1682 Sep  7 12:02 binstr.h
-rw-r--r-- 1 root root 1951 Sep  7 12:02 binwrap.h

/usr/local/lib $ ls -l | grep libbinio
-rw-r--r-- 1 root root   380720 Sep  7 12:02 libbinio.a
-rwxr-xr-x 1 root root      938 Sep  7 12:02 libbinio.la
lrwxrwxrwx 1 root root       17 Sep  7 12:02 libbinio.so -> libbinio.so.1.0.0
lrwxrwxrwx 1 root root       17 Sep  7 12:02 libbinio.so.1 -> libbinio.so.1.0.0
-rwxr-xr-x 1 root root   262540 Sep  7 12:02 libbinio.so.1.0.0

/usr/local/lib $ whereis libbinio
libbinio: /usr/local/lib/libbinio.la /usr/local/lib/libbinio.so /usr/local/lib/libbinio.a
```

**Comment by sneakernets** [comment]
I decided to run that code:

```
:~/Code $ g++ -o conftest -g -O2 -fPIC -I/usr/local/include -I/usr/local/include/libbinio -g -O2 -fPIC -fsigned-char test.cpp -lbz2 -lz  -L/usr/local/lib -ladplug -lbinio
:~/Code $ ./conftest
:~/Code $ echo $?
255
```

Sure enough, it's sending back -1!

**Comment by mywave82** [comment]
I will try to find time tomorrow to retest this on a Raspberry Pi, both with raspian system provided libbinio and a git clone from source.

**Comment by Malvineous** [comment]
@sneakernets Try `ldd ./conftest` to show which libraries it is picking up, to confirm it is using the versions you built in `/usr/local/lib` and not others somewhere else.

Would be interesting to print the return value (`printf("%d\n", f->readString(test, size));`) to see what it's actually coming back with.

I'd also suggest modifying `binstr.cpp` and adding a print statement to the `binisstream::getByte()` function, to both confirm it's working as expected and that the correct version is indeed being picked up (because if you run it and there's no output printed, you know for sure it's not using the correct code).

**Comment by sneakernets** [comment]
Sure, let me try that:
```
~/Code $ ldd ./conftest
	/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v6l.so (0xb6ed3000)
	libbz2.so.1.0 => /lib/arm-linux-gnueabihf/libbz2.so.1.0 (0xb6e98000)
	libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0xb6e6d000)
	libadplug-2.3.4-beta.so.0 => /usr/local/lib/libadplug-2.3.4-beta.so.0 (0xb6dd9000)
	libbinio.so.1 => /lib/arm-linux-gnueabihf/libbinio.so.1 (0xb6dbd000)
	libstdc++.so.6 => /lib/arm-linux-gnueabihf/libstdc++.so.6 (0xb6c76000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb6bf4000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb6bc7000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6a79000)
	/lib/ld-linux-armhf.so.3 (0xb6ee6000)
```

Ah ha! Let me try to remedy this.

**Comment by sneakernets** [comment]
Fixed, it was a really stupid oversight on my part - I forgot to run `ldconfig` after updating all the libraries. Usually that's run automatically but it wasn't in the case of libbinio ! Closing this.

**Comment by mywave82** [comment]
No problem. Please, can you leave a bug report in your distro to update their libbinio (and adplug) versions?

**Comment by sneakernets** [comment]
> No problem. Please, can you leave a bug report in your distro to update their libbinio (and adplug) versions?

Sure will! thanks for helping me out

**Comment by Malvineous** [comment]
Also that test script shouldn't include those two AdPlug header files, otherwise a broken AdPlug install could return a libbinio error which is misleading, so those two `#include` lines should be removed as well.  There should be a separate configure test for AdPlug.
