### ISSUE TITLE
building problems and a patch

### ISSUE THREAD

**Issue by alexmyczko** [mywave82/opencubicplayer#40]
here's a bugreport with a patch that you might want to review/upstream?

https://buildd.debian.org/status/package.php?p=ocp&suite=sid

**Comment by mywave82** [comment]
"mipsel", "alpha", "hppa", "powerpc" and "sparc64" build failure: problem with the debian build system (gcc-10 installed, but build seems to be forced to use gcc-11, configure failes early)

"hurd-i386": I do not know much about this, but seems they have an ALSA emulation layer (old version) on top of OSS. OpenCubicPlayer has recently removed support for old alsa versions to simplify the code a lot. Maybe drop ALSA support for hurd-i386 and only use the OSS, since ALSA is not native for this system anyway? Or does it provide some features not visible in the OSS like selecting sound-card?

"kfreebsd-amd64" and "kfreebsd-i386" build failure: problem with the debian build system (desktop-file-utils currently has broken dependencies)

Patches: currently debian only applies one patch that I can see: https://sources.debian.org/src/ocp/1:0.2.90-3/debian/patches/sidplayfp/
I have to check later why this is needed. I do not remember the configure magic sidplayfp receives from OCP.
