### ISSUE TITLE
Assertion failed: (samples <= self->cache_read_available)

### ISSUE THREAD

**Issue by kpstsp** [mywave82/opencubicplayer#57]
Time to time OCP die with message:

```
Assertion failed: (samples <= self->cache_read_available), function ringbuffer_tail_consume_samples, file ringbuffer.c, line 141.
```

Latest two time I catched it on Ultratracker's modules. Before I had same issue with another formats

==
version 0.2.97 (build from master:head)
Mac OS Catalina 10.15.7

curses mode in terminal

**Comment by mywave82** [comment]
Can you test one thing for me?

After you have done `./configure` , edit config.h manually and replace `#undef DISABLE_SIGALRM` with `#define DISABLE_SIGALRM 1`

If this works, I have to redo the mechanism that ensures that audio is produced even if waiting for I/O takes a long time etc.

**Comment by kpstsp** [comment]
In config.h this line is commented:

```
/* #undef DISABLE_SIGALRM */
```

in original config.h.in it not commented

**Comment by mywave82** [comment]
All the files that end with **.in** are template files that ./configure ( ./config.status to be exact ) reads in and modifies depending on tests and user-inputs.

All defines that ./configure might enable will in the .in file be   `/* #undef FOO */` and it can be replaced with `#define FOO 1` in the resulting file.

Can you manually in config.h after ./configure is ran, please replace that line with `#define DISABLE_SIGALRM 1` , since my main-suspect for the problem you experience is due to SIGLARM.

**Comment by mywave82** [comment]
That is great, then I know what I need to fix. The SIGALRM thingy was/is a mechanism to ensure that audio is generated even if there is heavy I/O load and application is stuttering, user is browsing network shares in the file browser etc

**Comment by mywave82** [comment]
The latest master should work, can you please test

**Comment by kpstsp** [comment]
Tested about 3 hrs. All ok, no crashes

**Comment by mywave82** [comment]
Thank you for testing and your patience
