### ISSUE TITLE
SDL2 on Wayland has various issues when switching visualization modes, resizing the window, etc.

### ISSUE THREAD

**Issue by cranderson** [mywave82/opencubicplayer#60]
There are various issues with the SDL2 version when toggling back and forth between different visualizations, like G, g, b, o, w, a, t.  Sometimes ocp crashes.  Other times there are lots of flickering/flashing effects after changing modes.  One time the audio output and visualizations froze although I could still change visualization modes.  Sometimes the flickering stops after switching modes again or resizing the text mode window.   Maximizing and restoring the window size is also problematic (Font size gets smaller in the maximized window, then much larger in the restored window.  Resizing the window by dragging a corner restores the original font size).  I cannot reproduce most of these issues with the X11 version.

Some outputs from various crashes:

free(): invalid pointer
Abort (core dumped)

corrupted double-linked list
Abort (core dumped)

Tested using 0.2.98 compiled on Fedora.  Build logs and packages here: https://koji.fedoraproject.org/koji/packageinfo?packageID=7114

**Comment by mywave82** [comment]
Audio-freezes can be issue that happens with libalsa and their libpulse audio redirection plugin when it looses audio-sync. Same as issue #8. I seem to reproduce it if rapidly changing display modes many times in a row, but problem seem to go away if using native soundcard in ALSA.

Regarding flickering, it should only flicker once when changing display mode. If multiple flickers happens, I do suspect a bad SDL2 display driver.

Font resizes - if you have selected a large font and resize the window so that width < 80 or height < 25 characters, a smaller font will temporary be selected - This is expected behaviour.

For the Abort crashes, these are interesting to retrieve some more information from. Please run   ./configure --with-debug   and do not strip the executables, and run ocp using valgrind           `valgrind ocp 2> log`

**Comment by mywave82** [comment]
Now we should only be left with your screen flickering and random crashes.

**Screen flickering:**
can you try to run SDL2 without wayland (I suspect this might be a cause)
[https://wiki.libsdl.org/FAQUsingSDL](https://wiki.libsdl.org/FAQUsingSDL)
You can start ocp like this: $ `SDL_VIDEODRIVER=x11 ocp-sdl2`


**Crashes:**
see above regarding valgrind and adding debug symbols to Open Cubic Player

**Comment by cranderson** [comment]
Confirmed that all these issues only happen with SDL2 on Wayland, tested both with <code>SDL_VIDEODRIVER=x11 ocp-sdl2</code> and <code>WAYLAND_DISPLAY= ocp-sdl2</code>.

**Comment by mywave82** [comment]
This probably falls into this category:
https://www.phoronix.com/scan.php?page=news_item&px=SDL2-Reverts-Wayland-Default

**Comment by mywave82** [comment]
Did the crashes go away as well when using X11 instead of wayland as the active SDL2 VIDEO driver?

**Comment by cranderson** [comment]
> Did the crashes go away as well when using X11 instead of wayland as the active SDL2 VIDEO driver?

Yes, except the wurfel mode one (issue #61).

**Comment by mywave82** [comment]
Could you retest the master to verify if this is fixed or still a problem?
